// ========================================
// PRODUTOS Natuhair
// ========================================

const produtosNatuhair = [

    {
        id: 701,
        nome: "Natuhair Óleo de Alecrim 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/alecrim.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Alho 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/alho.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Argan 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/argan.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo Azeite de Oliva 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/azeite-de-oliva.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Coco 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/coco.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo Dpantenol 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/dpantenol.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo Jojoba 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/jojoba.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Linhaça",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/linhaca.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Mandioca 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/mandioca.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Melaleuca 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/melaleuca.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Mix de Óleos 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/mix.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo Natuvin A 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/natuvim.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Rosa Mosqueta 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/rosa-mosqueta.jpe",
        destaque: false,
        esgotado: false
    },
    {
        id: 701,
        nome: "Natuhair Óleo de Semente de Uva 60ml",
        marca: "Natuhair",
        linha: "Óleos Capilares",
        tipo: "cabelo",
        categoria: "Óleo Capilar",
        descricao: "Óleo Capilar 60ml",
        preco: "R$ 12,49",
        imagem: "img/natuhair/oleo-capilar/uva.jpe",
        destaque: false,
        esgotado: false
    },
];